name: Generate DOCX and EPUB

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  generate-content:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Generate DOCX file
        run: |
          cd src/
          pandoc --syntax-definition="zig.xml" --highlight-style="zig.theme" *.md -o learning-zig.ru.docx

      - name: Generate EPUB file
        run: |
          cd src/
          pandoc --syntax-definition="zig.xml" --highlight-style="zig.theme" zig.yaml *.md -o learning-zig.ru.epub

      - name: Generate LaTeX file
        run: |
          cd src/
          pandoc --syntax-definition="zig.xml" --highlight-style="zig.theme" *.md -o learning-zig.ru.tex --standalone --to=latex -V documentclass=report -V lang=ru -V mainfont="DejaVu Serif" -V monofont="DejaVu Sans Mono" -V geometry:"left=10mm, right=10mm, top=20mm, bottom=25mm" --toc --number-sections

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: learning-zig-output
          path: |
            src/learning-zig.ru.docx
            src/learning-zig.ru.epub
            src/learning-zig.ru.tex